[package]
name = "f3l_features"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
f3l_core = { path = "../f3l_core"}
f3l_search_tree = { path = "../f3l_search_tree" }
rand = "0.8"
