[package]
name = "f3l_search_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
f3l_core = { path = "../f3l_core"}
rayon = "1.8"

[dev-dependencies]
glam = "0.25.0"
nalgebra = { version = "0.32", features = ["glam025"]}
approx = "0.5"