[package]
name = "f3l_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
f3l_glam = {path = "../f3l_glam"}
num-traits = "0.2.17"
rayon = "1.8"